// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace, KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";

declare global {
  interface Env {
    DAY_SLOT: __TelnyxActorNamespace;
    CACHE: __TelnyxKvNamespace;
    SECRETS: { get(binding: "ACTOR_PROXY_SECRET" | "WEBHOOK_TOKEN"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    DAY_SLOT: __TelnyxActorNamespace;
    CACHE: __TelnyxKvNamespace;
    SECRETS: { get(binding: "ACTOR_PROXY_SECRET" | "WEBHOOK_TOKEN"): Promise<string> };
  }
}

export {};
