// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";

declare global {
  interface Env {
    CACHE: __TelnyxKvNamespace;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    CACHE: __TelnyxKvNamespace;
  }
}

export {};
