// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { DaySlotActor } from "./src/index";

declare global {
  interface Env {
    DAY_SLOT: __TelnyxActorNamespace<DaySlotActor>;
    SECRETS: { get(binding: "ACTOR_PROXY_SECRET"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    DAY_SLOT: __TelnyxActorNamespace<DaySlotActor>;
    SECRETS: { get(binding: "ACTOR_PROXY_SECRET"): Promise<string> };
  }
}

export {};
