// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { DaySlotActor } from "./src/index";

declare global {
  interface Env {
    DAY_SLOT: __TelnyxActorNamespace<DaySlotActor>;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    DAY_SLOT: __TelnyxActorNamespace<DaySlotActor>;
  }
}

export {};
